#ifndef NUKLEAR_HEADER_H
#define NUKLEAR_HEADER_H

// so we always have matching defines

#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
//#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_INCLUDE_STANDARD_VARARGS
//#define NK_BUTTON_TRIGGER_ON_RELEASE

#include <nuklear.h>

#endif